name: ansible-test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ansible_collections/shaps/ipset
    - name: Setup python
      uses: actions/setup-python@v1

    - name: Install ansible and test requirements
      run: pip install ansible pycodestyle pylint rstcheck virtualenv voluptuous yamllint

    - name: Run sanity tests
      run: ansible-test sanity
      working-directory: ansible_collections/shaps/ipset

    - name: Run integration tests
      run: ansible-test integration
      working-directory: ansible_collections/shaps/ipset
